# Generated by Django 4.0.6 on 2022-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(choices=[(0, 'Nul'), (1, 'Mauvais'), (2, 'Moyen'), (3, 'Bon'), (4, 'Très bon'), (5, 'Excellent')]),
        ),
    ]
