# Generated by Django 4.0.6 on 2022-07-17 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(0, 'Nul'), (1, 'Mauvais'), (2, 'Moyen'), (3, 'Bon'), (4, 'Très bon'), (5, 'Excellent')], max_length=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
