# Generated by Django 4.0.6 on 2022-07-31 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_alter_userfollow_followed_user_alter_userfollow_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFollow',
            new_name='UserFollows',
        ),
    ]
