# Generated by Django 4.0.6 on 2022-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de profil'),
        ),
    ]
