# Generated by Django 4.0.6 on 2022-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='Photo de profil'),
            preserve_default=False,
        ),
    ]
